### ISSUE TITLE
cannot import name 'torchvision_ssl_encoder'

### ISSUE THREAD

**Issue by hrnademi** [PyTorchLightning/pytorch-lightning-bolts#210]
Hi 
I just want to run following example, but I get this error "cannot import name 'torchvision_ssl_encoder'"

```
from pl_bolts.utils.self_supervised import torchvision_ssl_encoder

resnet = torchvision_ssl_encoder('resnet18', pretrained=False, return_all_feature_maps=True)
x = torch.rand(3, 3, 32, 32)

feat_maps = resnet(x)
```

Is something wrong with pytorch-lightning-bolts?

**Comment by Borda** [comment]
@hrnademi can you share the exact message and some more details about your local env?

**Comment by ananyahjha93** [comment]
@hrnademi 
I think torchvision_ssl_encoder is an internal function and thus hasn't been exported in utils/__init__.py. You can use the docs here: https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html to import the available pre-trained self-supervised learning models present.

**Comment by Borda** [comment]
I can confirm this issue on master
```
>>> from pl_bolts.utils.self_supervised import torchvision_ssl_encoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jirka/Workspace/pytorch-lightning-bolts/pl_bolts/utils/self_supervised.py", line 1, in <module>
    from pl_bolts.models.self_supervised import resnets
  File "/Users/jirka/Workspace/pytorch-lightning-bolts/pl_bolts/models/self_supervised/__init__.py", line 21, in <module>
    from pl_bolts.models.self_supervised.amdim.amdim_module import AMDIM
  File "/Users/jirka/Workspace/pytorch-lightning-bolts/pl_bolts/models/self_supervised/amdim/__init__.py", line 1, in <module>
    from pl_bolts.models.self_supervised.amdim.amdim_module import AMDIM
  File "/Users/jirka/Workspace/pytorch-lightning-bolts/pl_bolts/models/self_supervised/amdim/amdim_module.py", line 16, in <module>
    from pl_bolts.utils.self_supervised import torchvision_ssl_encoder
ImportError: cannot import name 'torchvision_ssl_encoder' from 'pl_bolts.utils.self_supervised' (/Users/jirka/Workspace/pytorch-lightning-bolts/pl_bolts/utils/self_supervised.py)
```
seems like we have cyclic import somewhere...

**Comment by MaveriQ** [comment]
I have bolts version '0.3.4' and I am still getting the error.
