### ISSUE TITLE
Pretrained AE `resnet50-imagenet` is unavailable

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#224]
## 🐛 Bug
I am following the example on [doc](https://pytorch-lightning-bolts.readthedocs.io/en/latest/autoencoders.html), and it seems there is not "resnet50-imagenet" pretrained model as I get the error shown below:
```shell
Traceback (most recent call last):
  File "/tmp/a.py", line 19, in <module>
    model = model.from_pretrained('resnet50-imagenet')
  File "/home/nitta/.pyenv/versions/anaconda3-5.3.1/envs/bolts/lib/python3.8/site-packages/pl_bolts/models/autoencoders/basic_ae/basic_ae_module.py", line 94, in from_pretrained
    raise KeyError(str(checkpoint_name) + ' not present in pretrained weights.')
KeyError: 'resnet50-imagenet not present in pretrained weights.'
```

### To Reproduce
Minimal code to reproduce:
```python
from pl_bolts.models.autoencoders import AE
model = AE(input_height=32)
model = model.from_pretrained("resnet50-imagenet")
```

**Comment by akihironitta** [comment]
Just created a PR #225 to fix the AE example as well as the VAE example.
